### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by CristhianUNSa** [lore/www.lorejs.org#21]
URL: http://www.lorejs.org/quickstart/data/overview/

When clicking on the link "read more about about in the docs" in that URL, it take you to "http://localhost:4000/features/foundation/data-structure/" instead of "http://www.lorejs.org/features/foundation/data-structure/"

**Comment by jchansen** [comment]
@CristhianUNSa thanks!

I fixed the link. Appreciate you letting me know.
