### ISSUE TITLE
Numbering is wrong on the list for the data structure section

### ISSUE THREAD

**Issue by hjamal** [lore/www.lorejs.org#9]
See image below:
<img width="202" alt="screen shot 2016-11-24 at 1 51 30 pm" src="https://cloud.githubusercontent.com/assets/4442559/20609724/455ffa5a-b24d-11e6-8754-4b961310b16c.png">

**Comment by jchansen** [comment]
Nice catch @hjamal. Thanks! Numbering is fixed now.
